<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Description>A local stored Password Manager GUI.</Description>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Upsilon.Apps.Passkey.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <None Update="raw\u75-JVnHlT0oH7p-JSWAY9vIpVxbn9-NM07NZKjX2JgMb27gRXv0lrz-dHmR90FEbxgUIiZ436dFfxrTpvhIsw==.pku">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
